name: G.D.R Verdena

# Add your google-analytics ID here to activate google analytics
google_analytics:  UA-177352589-1 # out your google-analytics code

markdown: kramdown
syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
