name: G.D.R Verdena
title:              G.D.R Verdena
email:              g.d.verderena@gmail.com
description:        Grupo Desportivo, Recreativo e Cultural
author:             G.D.R Verdena
baseurl:            "/"
url:                "https://gdr-verderena.github.io"
image:  https://raw.githubusercontent.com/GDR-Verderena/gdr-verderena.github.io/master/assets/img/logo.jpg

# Social Profiles

github_username:    GDR-Verderena
facebook_username:  G. D. R. Verderena


# Add your google-analytics ID here to activate google analytics
google_analytics:  UA-177352589-1 # out your google-analytics code

markdown: kramdown
syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
  
  # SEO/OpenGraph
logo: https://raw.githubusercontent.com/GDR-Verderena/gdr-verderena.github.io/master/assets/img/logo.jpg

lang: pt_PT

name: GDR Verderena
  links:
    - https://www.facebook.com/gdr.verderena/
    - https://github.com/GDR-Verderena
author:
  twitter: GDR Verderena

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.jpg
      author: GDR Verderena
      
      
      
# /SEO
...
